version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 1.0.0
    commands:
      # Install AWS CLI (if needed)
      - echo Installing dependencies...
      - pip install --upgrade awscli
      - terraform --version

  pre_build:
    commands:
      - echo Setting up Terraform...
      - terraform init

  build:
    commands:
      - echo Running Terraform plan...
      - terraform plan

  post_build:
    commands:
      - echo Applying Terraform...
      - terraform apply -auto-approve
