version: 0.2

phases:
  install:
    runtime-versions:
      # No need to specify a specific runtime as we'll install Terraform manually
    commands:
      - echo "Installing Terraform"
      - curl -LO https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
      - unzip terraform_1.5.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version  # Check Terraform version
  build:
    commands:
      - echo "Running Terraform Plan"
      - terraform --version
